export const SET_USER_INFO = Symbol('SET_INFO')
export const SET_RATES = Symbol('SET_RATES')
export const ADD_CATEGORY = Symbol('ADD_CATEGORY')
export const SET_CATEGORIES = Symbol('SET_CATEGORIES')
export const UPDATE_CATEGORY = Symbol('UPDATE_CATEGORY')
export const CREATE_RECORD = Symbol('CREATE_RECORD')
export const SET_RECORDS = Symbol('SET_RECORDS')
